version: "3.8"

services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH: "false"

  auth-service:
    build: ./auth-service
    ports:
      - "5001:5001"
    env_file:
      - ./auth-service/.env
    depends_on:
      - mongodb

  product-service:
    build: ./product-service
    ports:
      - "5002:5002"
    env_file:
      - ./product-service/.env
    depends_on:
      - mongodb

  ai-service:
    build: ./ai-service
    ports:
      - "5003:5003"
    env_file:
      - ./ai-service/.env
    depends_on:
      - product-service

  gateway:
    build: ./gateway
    ports:
      - "5000:5000"
    depends_on:
      - auth-service
      - product-service
      - ai-service

volumes:
  mongo-data: